In [3]:
import pandas as pd

In [14]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/'
url = f'{prefix}/yellow_tripdata_2021-01.csv.gz'

In [15]:
df = pd.read_csv(url)

/tmp/ipykernel_3235/4176769558.py:1: DtypeWarning: Columns (0: store_and_fwd_flag) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

In [17]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2021-01-01 00:30:10,2021-01-01 00:36:12,1.0,2.10,1.0,N,142,43,2.0,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1.0,2021-01-01 00:51:20,2021-01-01 00:52:19,1.0,0.20,1.0,N,238,151,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1.0,2021-01-01 00:43:30,2021-01-01 01:11:06,1.0,14.70,1.0,N,132,165,1.0,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1.0,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.60,1.0,N,138,132,1.0,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2.0,2021-01-01 00:31:49,2021-01-01 00:48:21,1.0,4.94,1.0,N,68,33,1.0,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [19]:
len(df)

1369765

In [27]:
df.dtypes

VendorID                 float64
tpep_pickup_datetime         str
tpep_dropoff_datetime        str
passenger_count          float64
trip_distance            float64
RatecodeID               float64
store_and_fwd_flag           str
PULocationID               int64
DOLocationID               int64
payment_type             float64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
improvement_surcharge    float64
total_amount             float64
congestion_surcharge     float64
dtype: object

In [28]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates
)

In [30]:
df['tpep_pickup_datetime']

0         2021-01-01 00:30:10
1         2021-01-01 00:51:20
2         2021-01-01 00:43:30
3         2021-01-01 00:15:48
4         2021-01-01 00:31:49
                  ...
1369760   2021-01-25 08:32:04
1369761   2021-01-25 08:34:00
1369762   2021-01-25 08:37:00
1369763   2021-01-25 08:28:00
1369764   2021-01-25 08:38:00
Name: tpep_pickup_datetime, Length: 1369765, dtype: datetime64[us]

In [31]:
!uv add sqlalchemy

Resolved 117 packages in 1.92s
Prepared 2 packages in 182ms
░░░░░░░░░░░░░░░░░░░░ [0/2] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 2 packages in 202ms
 + greenlet==3.5.0
 + sqlalchemy==2.0.49

In [32]:
!uv add psycopg2-binary

Resolved 118 packages in 229ms
Prepared 1 package in 82ms
░░░░░░░░░░░░░░░░░░░░ [0/1] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 1 package in 30ms.12
 + psycopg2-binary==2.9.12

In [33]:
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg://root:root@localhost:5432/ny_taxi')

In [38]:
df.head(0)

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge]
Index: []

In [35]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [39]:
df.head(0).to_sql( name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [40]:
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates = parse_dates,
    iterator = True,
    chunksize = 100000,
)

In [51]:
from tqdm.auto import tqdm

In [54]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql( name='yellow_taxi_data', con=engine, if_exists='append')
    print(len(df_chunk))

0it [00:00, ?it/s]

In [46]:
df = next(df_iter)

In [47]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
100000,2,2021-01-04 14:42:51,2021-01-04 14:51:18,1,1.43,1,N,170,161,2,7.5,0.0,0.5,0.00,0.0,0.3,10.80,2.5
100001,2,2021-01-04 14:04:39,2021-01-04 14:18:41,1,2.82,1,N,170,143,2,12.0,0.0,0.5,0.00,0.0,0.3,15.30,2.5
100002,1,2021-01-04 14:12:49,2021-01-04 14:31:21,0,2.70,1,N,68,239,1,13.5,2.5,0.5,3.35,0.0,0.3,20.15,2.5
100003,1,2021-01-04 14:43:55,2021-01-04 14:48:45,1,0.70,1,N,246,68,2,5.5,2.5,0.5,0.00,0.0,0.3,8.80,2.5
100004,1,2021-01-04 14:59:16,2021-01-04 15:07:08,1,1.60,1,N,161,234,1,8.0,2.5,0.5,2.25,0.0,0.3,13.55,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,1,2021-01-06 17:02:39,2021-01-06 17:09:21,2,1.10,1,N,236,237,1,6.5,3.5,0.5,3.20,0.0,0.3,14.00,2.5
199996,1,2021-01-06 17:12:00,2021-01-06 17:17:55,1,1.60,1,N,237,239,1,7.0,3.5,0.5,2.25,0.0,0.3,13.55,2.5
199997,2,2021-01-06 17:03:41,2021-01-06 17:07:37,2,1.06,1,N,161,186,1,5.5,1.0,0.5,1.96,0.0,0.3,11.76,2.5
199998,2,2021-01-06 17:14:11,2021-01-06 17:29:58,2,5.24,1,N,68,238,1,18.0,1.0,0.5,1.00,0.0,0.3,23.30,2.5
199999,2,2021-01-06 17:45:43,2021-01-06 17:52:37,2,1.49,1,N,68,114,1,7.0,1.0,0.5,1.50,0.0,0.3,12.80,2.5

In [55]:
for df_chunk in df_iter:
    print("starting insert...")

    df_chunk.to_sql(
        name='yellow_taxi_data',
        con=engine,
        if_exists='append',
        index=False,
        method='multi'
    )

    print(f"inserted {len(df_chunk)} rows")
    break

In [56]:
engine

Engine(postgresql+psycopg://root:***@localhost:5432/ny_taxi)

In [57]:
with engine.connect() as conn:
    print("connected!")

connected!

In [68]:
df_iter = pd.read_csv(
    'yellow_tripdata_2021-01.csv',
    iterator=True,
    chunksize=100000
)

FileNotFoundError: [Errno 2] No such file or directory: 'yellow_tripdata_2021-01.csv'

In [61]:
import os
os.getcwd()

'/workspaces/data-engineering-workshop/pipeline'

In [62]:
os.listdir()

['.venv',
 'Notebook.ipynb',
 'main.py',
 'pipeline.py',
 '.python-version',
 '.ipynb_checkpoints',
 'uv.lock',
 'README.md',
 'output_12.parquet',
 'Dockerfile',
 'pyproject.toml']

In [63]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
1300000,<NA>,2021-01-05 10:38:40,2021-01-05 10:46:20,<NA>,1.30,<NA>,<NA>,170,161,<NA>,7.00,0.0,0.5,1.03,0.00,0.3,11.33,2.5
1300001,<NA>,2021-01-05 10:17:14,2021-01-05 10:41:21,<NA>,7.90,<NA>,<NA>,216,198,<NA>,31.49,0.0,0.5,2.75,0.00,0.3,35.04,0.0
1300002,<NA>,2021-01-05 10:39:00,2021-01-05 10:46:00,<NA>,0.98,<NA>,<NA>,62,62,<NA>,16.23,0.0,0.5,2.75,0.00,0.3,19.78,0.0
1300003,<NA>,2021-01-05 10:05:00,2021-01-05 10:19:00,<NA>,1.59,<NA>,<NA>,85,71,<NA>,13.45,0.0,0.5,2.75,0.00,0.3,17.00,0.0
1300004,<NA>,2021-01-05 10:18:08,2021-01-05 10:41:40,<NA>,9.87,<NA>,<NA>,236,208,<NA>,30.23,0.0,0.5,2.75,6.12,0.3,39.90,0.0

In [65]:
test_df = df.head(100)

In [66]:
test_df.to_sql(
    name='yellow_taxi_data',
    con=engine,
    if_exists='append',
    index=False
)

-1

In [67]:
for df_chunk in df_iter:
    df_chunk.to_sql(
        name='yellow_taxi_data',
        con=engine,
        if_exists='append',
        index=False,
        method='multi'
    )

In [69]:
import glob
print(glob.glob("**/*.csv", recursive=True))

[]